# Generated by Django 5.2 on 2025-07-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.FloatField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotId', models.IntegerField()),
                ('Status', models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('reel', models.TextField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
                ('scene', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShotAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.FloatField(default=1.0)),
                ('assignedDate', models.TextField(blank=True, null=True)),
                ('dueDate', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='TODO', max_length=20)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.client')),
            ],
        ),
    ]
