# Generated by Django 5.2 on 2025-05-31 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ProjectName', models.TextField()),
                ('Status', models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'In Progress'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('StartDate', models.DateTimeField(blank=True, null=True)),
                ('ClientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotId', models.IntegerField()),
                ('Status', models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'In Progress'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('reel', models.TextField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
                ('scene', models.TextField(blank=True, null=True)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.project')),
            ],
            options={
                'unique_together': {('shotId', 'ProjectId')},
            },
        ),
        migrations.CreateModel(
            name='ShotAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.FloatField(default=1.0)),
                ('assignedFrom', models.TextField(blank=True, null=True)),
                ('assignedDate', models.TextField(blank=True, null=True)),
                ('dueDate', models.TextField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.department')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.shot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('version', 'shot', 'user', 'dept')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.FloatField()),
                ('comment', models.TextField()),
                ('shot_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.shotassociation')),
            ],
        ),
    ]
