# Generated by Django 5.2 on 2025-07-30 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_management', '0001_initial'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.department'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.project'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shot',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='task_management.project'),
        ),
        migrations.AddField(
            model_name='shotassociation',
            name='assigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_assigned_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shotassociation',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.shot'),
        ),
        migrations.AddField(
            model_name='shotassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='shot_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.shotassociation'),
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('shotId', 'ProjectId')},
        ),
        migrations.AlterUniqueTogether(
            name='shotassociation',
            unique_together={('version', 'shot', 'user')},
        ),
    ]
