# Generated by Django 5.2 on 2025-07-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotassociation',
            name='assignedFrom',
        ),
        migrations.AddField(
            model_name='shotassociation',
            name='assigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_assigned_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shotassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
