# Generated by Django 5.2 on 2025-07-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_remove_shotassociation_assignedfrom_and_more'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ClientID',
            new_name='clientID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ClientID',
            new_name='clientID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='DueDate',
            new_name='dueDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectName',
            new_name='projectName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='StartDate',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ProjectID',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Status',
        ),
        migrations.AlterUniqueTogether(
            name='shotassociation',
            unique_together={('version', 'shot', 'user')},
        ),
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN_PROGRESS'), ('IN REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='TODO', max_length=20),
        ),
        migrations.RemoveField(
            model_name='shotassociation',
            name='dept',
        ),
    ]
