# Generated by Django 5.2 on 2025-07-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='task_management.project'),
        ),
    ]
