# Generated by Django 5.2 on 2025-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_shot_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='Status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN_PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20),
        ),
    ]
