# Generated by Django 5.2 on 2025-05-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deptName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ProjectName', models.TextField()),
                ('Status', models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'In Progress'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('StartDate', models.DateTimeField(blank=True, null=True)),
                ('ClientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.client')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('contact', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField()),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotId', models.IntegerField()),
                ('Status', models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'In Progress'), ('IN REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('reel', models.TextField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
                ('scene', models.TextField(blank=True, null=True)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project')),
            ],
            options={
                'unique_together': {('shotId', 'ProjectId')},
            },
        ),
    ]
