# Generated by Django 5.2 on 2025-05-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
